### ISSUE TITLE
Crashing when creepers explode

### ISSUE THREAD

**Issue by Richtofhen** [AzureDoom/Totally-Enough-Pain#4]
[crash-2022-06-20_20.54.04-server.txt](https://github.com/AzureDoom/Totally-Enough-Pain/files/8943082/crash-2022-06-20_20.54.04-server.txt)

I saw that someone had the same issue but there's no fix to it in his topic

**Comment by AzureDoom** [comment]
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1927::method_8350(Z)V has incompatible changes at opcode 279 in callback Professions.mixins.json:TntExplosionTriggerMixin from mod professions->@Inject::onExploded(ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ZLit/unimi/dsi/fastutil/objects/ObjectArrayList;Ljava/util/Iterator;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lnet/minecraft/class_2248;)V.
`
Not an issue with my mod. Professions issue.
